add colors, git and rvm information

diff --git a/dotfiles/bash/config b/dotfiles/bash/config
--- a/dotfiles/bash/config
+++ b/dotfiles/bash/config
@@ -1,67 +1,61 @@
-# colors from http://wiki.archlinux.org/index.php/Color_Bash_Prompt
-# misc
-NO_COLOR='\e[0m' #disable any colors
+. ~/bin/dotfiles/bash/colors
 
-# regular colors
-BLACK='\e[0;30m'
-RED='\e[0;31m'
-GREEN='\e[0;32m'
-YELLOW='\e[0;33m'
-BLUE='\e[0;34m'
-MAGENTA='\e[0;35m'
-CYAN='\e[0;36m'
-WHITE='\e[0;37m'
+function parse_git_branch {
+  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
+}
+ps1_git()
+{
+  local branch="" sha1="" line="" attr="" color=0
 
-# emphasized (bolded) colors
-EBLACK='\e[1;30m'
-ERED='\e[1;31m'
-EGREEN='\e[1;32m'
-EYELLOW='\e[1;33m'
-EBLUE='\e[1;34m'
-EMAGENTA='\e[1;35m'
-ECYAN='\e[1;36m'
-EWHITE='\e[1;37m'
+  shopt -s extglob # Important, for our nice matchers :)
 
-# underlined colors
-UBLACK='\e[4;30m'
-URED='\e[4;31m'
-UGREEN='\e[4;32m'
-UYELLOW='\e[4;33m'
-UBLUE='\e[4;34m'
-UMAGENTA='\e[4;35m'
-UCYAN='\e[4;36m'
-UWHITE='\e[4;37m'
+  command -v git >/dev/null 2>&1 || {
+    printf " \033[1;37m\033[41m[git not found]\033[m "
+    return 0
+  }
 
-# background colors
-BBLACK='\e[40m'
-BRED='\e[41m'
-BGREEN='\e[42m'
-BYELLOW='\e[43m'
-BBLUE='\e[44m'
-BMAGENTA='\e[45m'
-BCYAN='\e[46m'
-BWHITE='\e[47m'
+  branch=$(git symbolic-ref -q HEAD 2>/dev/null)
+
+  (( $? > 0 )) && return 0 # Not in a git repo, no need to continue.
+
+  branch=${branch##refs/heads/}
+
+  # Now we display the branch.
+  sha1=$(git rev-parse --short --quiet HEAD)
+
+  case "${branch:-"(no branch)"}" in
+   production|prod) attr="1;37m\033[" ; color=41 ;; # red
+   master|deploy)   color=31                     ;; # red
+   stage|staging)   color=33                     ;; # yellow
+   dev|development) color=34                     ;; # blue
+   next)            color=36                     ;; # gray
+   *)
+     if [[ -n "${branch}" ]] ; then # Feature Branch :)
+       color=32 # green
+     else
+       color=0 # reset
+     fi
+     ;;
+  esac
+
+  [[ $color -gt 0 ]] &&
+    printf " \033[${attr}${color}m(${branch}$(ps1_git_status):$sha1)\033[0m"
+}
+
+ps1_git_status()
+{
+  local git_status="$(git status 2>/dev/null)"
+
+  [[ "${git_status}" = *deleted* ]]                    && printf "%s" "-"
+  [[ "${git_status}" = *Untracked[[:space:]]files:* ]] && printf "%s" "+"
+  [[ "${git_status}" = *modified:* ]]                  && printf "%s" "*"
+}
+
+ps1_rvm()
+{
+  command -v rvm-prompt >/dev/null 2>&1 && printf "%s" " $(rvm-prompt) "
+}
 
 # Update the command prompt to be <user>:<current_directory>(git_branch) >
 # Note that the git branch is given a special color
-PS1="\n\u:\w \[$EBLACK\]\$(pwd)\[$NO_COLOR\] \n→ "
-#PS1="\n\[$EBLACK\][ \[$YELLOW\]\u@\h\[$NO_COLOR\] \[$BLUE\]\w \[$EBLACK\]]\$(ps1_git)\[$GREEN\]\$(ps1_rvm)\n\[$EBLACK\][\[$ERED\] \T \[$EBLACK\]] \[$NO_COLOR\]$ "
-
-#PS1="\[$BLUE\]\w\[$RED\]\$(parse_git_branch)\n\[$GREEN\]\u@\h\[$WHITE\]$ "
-
-PS2='> '
-PS4='+ '
-
-#unset PROMPT_COMMAND
-#if [ "$SHELL" = '/bin/bash' ]
-#then
-#    case $TERM in
-#         rxvt|*term)
-#            set -o functrace
-#            trap 'echo -ne "\e]0;$BASH_COMMAND\007"' DEBUG
-#            export PS1="\e]0;$TERM\007$PS1"
-#         ;;
-#    esac
-#fi
-PROMPT_COMMAND='echo -ne "\033]0;${USER}: ${PWD/$HOME/~}\007"'
-#PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/~}\007"'.
+PS1="\n\[$GREEN\]\u:\w \$(ps1_git)\[$BLUE\]\$(ps1_rvm)\[$NO_COLOR\] \n→ "
